### ISSUE TITLE
The chia_location in your config.yaml does not exist.

### ISSUE THREAD

**Issue by 3rtgrl** [swar/Swar-Chia-Plot-Manager#697]
I am doing all the settings according to the guide, but it gives the following error, i changed the new chia version directory

Python version 3.9.5
Chia version 1.1.6

--Error--
File "c:\Swar-Chia-Plot-Manager-main\manager.py", line 30, in <module>
    start_manager()
  File "c:\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 39, in start_manager
    test_configuration(chia_location=chia_location, notification_settings=notification_settings,
  File "c:\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\configuration.py", line 8, in test_configuration
    raise InvalidChiaLocationException('The chia_location in your config.yaml does not exist. Please confirm if '
plotmanager.library.utilities.exceptions.InvalidChiaLocationException: The chia_location in your config.yaml does not exist. Please confirm if you have the right version. Also confirm if you have a space after the colon. "chia_location: <DRIVE>" not "chia_location:<DRIVE>"

[config.txt](https://github.com/swar/Swar-Chia-Plot-Manager/files/6523579/config.txt)

**Comment by damonsro** [comment]
remplaza la linea:
chia_location: C:\Users\Ertuğrul\AppData\Local\chia-blockchain\app-1.1.6\resources\app.asar.unpacked\daemon
por:
chia_location: C:\Users\Ertuğrul\AppData\Local\chia-blockchain\app-1.1.6\resources\app.asar.unpacked\daemon\chia.exe

**Comment by 3rtgrl** [comment]
I fixed the field you wrote gives the following error

Traceback (most recent call last):
  File "c:\Swar-Chia-Plot-Manager-main\manager.py", line 30, in <module>
    start_manager()
  File "c:\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 35, in start_manager
    instrumentation_settings = get_config_info()
  File "c:\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 138, in get_config_info
    config = _get_config()
  File "c:\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 16, in _get_config
    config = yaml.load(stream=f, Loader=yaml.Loader)
  File "C:\Program Files\Python39\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Program Files\Python39\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Program Files\Python39\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Program Files\Python39\lib\site-packages\yaml\composer.py", line 58, in compose_document
    self.get_event()
  File "C:\Program Files\Python39\lib\site-packages\yaml\parser.py", line 118, in get_event
    self.current_event = self.state()
  File "C:\Program Files\Python39\lib\site-packages\yaml\parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "C:\Program Files\Python39\lib\site-packages\yaml\scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "C:\Program Files\Python39\lib\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "C:\Program Files\Python39\lib\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "C:\Swar-Chia-Plot-Manager-main\config.yaml", line 10, column 8

**Comment by picposter** [comment]
Check Line 10 in config.yaml as last error line says

**Comment by 3rtgrl** [comment]
line10 corresponds to the area I specified but I did not understand what to do

![image](https://user-images.githubusercontent.com/84584768/119190441-08be3800-ba86-11eb-8e62-2d6cd1900d66.png)

**Comment by spacewaffles309** [comment]
it may sound silly, but some other members have seen similar issues just due to characters and formatting:  can you verify that there aren't any blank spaces or characters after the colon on line 10?  and maybe even copy/paste the entire `manager:` section from the default file over top of that one?

only suggesting this because i've seen posts in the past where it was just a case of a weird layout in the text itself, not a 'real' error.

**Comment by andrefelipeml** [comment]
I'm having the same problem, it's a special character in "chia_location". but I still can't solve
